// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqhandlebars.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import aqhandlebars.proxies.constants.Constants;
import aqhandlebars.ICustomHelperRegister;

public class CustomHelperRegisterClassIsValid extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.String ClassName;

	public CustomHelperRegisterClassIsValid(
		IContext context,
		java.lang.String _className
	)
	{
		super(context);
		this.ClassName = _className;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		try{
			Class<?> formatterClass = Class.forName(this.ClassName);
			Boolean implementsInterface = ICustomHelperRegister.class.isAssignableFrom(formatterClass);
			
			return implementsInterface;
		}
		catch(Exception ex){
			_log.error("CustomHelperRegisterClassIsValid.execute() || failed with error '" + ex.getMessage() + "'");
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CustomHelperRegisterClassIsValid";
	}

	// BEGIN EXTRA CODE
	private ILogNode _log = Core.getLogger(Constants.getLogNodeName());	
	// END EXTRA CODE
}
