// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqhandlebars.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import aqhandlebars.HandlebarManager;

public class GenerateForExportDocumentAndObject extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String Template;
	private final java.lang.String JsonExportMapping;
	private final IMendixObject ExportRootObject;
	/** @deprecated use com.mendix.utils.ListUtils.map(PartialTemplates, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __PartialTemplates;
	private final java.util.List<aqhandlebars.proxies.PartialTemplate> PartialTemplates;

	public GenerateForExportDocumentAndObject(
		IContext context,
		java.lang.String _template,
		java.lang.String _jsonExportMapping,
		IMendixObject _exportRootObject,
		java.util.List<IMendixObject> _partialTemplates
	)
	{
		super(context);
		this.Template = _template;
		this.JsonExportMapping = _jsonExportMapping;
		this.ExportRootObject = _exportRootObject;
		this.__PartialTemplates = _partialTemplates;
		this.PartialTemplates = java.util.Optional.ofNullable(_partialTemplates)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(partialTemplatesElement -> aqhandlebars.proxies.PartialTemplate.initialize(getContext(), partialTemplatesElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		HandlebarManager handlebarManager = new HandlebarManager(getContext(), JsonExportMapping, ExportRootObject, PartialTemplates);
		String output = handlebarManager.generateFromTemplate(Template);
		
		return output;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateForExportDocumentAndObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
