// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treeview.proxies;

public class TreeDisplayContext implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject treeDisplayContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TreeView.TreeDisplayContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TreeDisplayContext_TreeItem_Selected("TreeView.TreeDisplayContext_TreeItem_Selected"),
		TreeDisplayContext_Tree("TreeView.TreeDisplayContext_Tree");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TreeDisplayContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TreeDisplayContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject treeDisplayContextMendixObject)
	{
		if (treeDisplayContextMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, treeDisplayContextMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.treeDisplayContextMendixObject = treeDisplayContextMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static treeview.proxies.TreeDisplayContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new treeview.proxies.TreeDisplayContext(context, mendixObject);
	}

	public static treeview.proxies.TreeDisplayContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return treeview.proxies.TreeDisplayContext.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TreeDisplayContext_TreeItem_Selected
	 */
	public final treeview.proxies.TreeItem getTreeDisplayContext_TreeItem_Selected() throws com.mendix.core.CoreException
	{
		return getTreeDisplayContext_TreeItem_Selected(getContext());
	}

	/**
	 * @param context
	 * @return value of TreeDisplayContext_TreeItem_Selected
	 * @throws com.mendix.core.CoreException
	 */
	public final treeview.proxies.TreeItem getTreeDisplayContext_TreeItem_Selected(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeview.proxies.TreeItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TreeDisplayContext_TreeItem_Selected.toString());
		if (identifier != null) {
			result = treeview.proxies.TreeItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TreeDisplayContext_TreeItem_Selected
	 * @param treedisplaycontext_treeitem_selected
	 */
	public final void setTreeDisplayContext_TreeItem_Selected(treeview.proxies.TreeItem treedisplaycontext_treeitem_selected)
	{
		setTreeDisplayContext_TreeItem_Selected(getContext(), treedisplaycontext_treeitem_selected);
	}

	/**
	 * Set value of TreeDisplayContext_TreeItem_Selected
	 * @param context
	 * @param treedisplaycontext_treeitem_selected
	 */
	public final void setTreeDisplayContext_TreeItem_Selected(com.mendix.systemwideinterfaces.core.IContext context, treeview.proxies.TreeItem treedisplaycontext_treeitem_selected)
	{
		if (treedisplaycontext_treeitem_selected == null) {
			getMendixObject().setValue(context, MemberNames.TreeDisplayContext_TreeItem_Selected.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TreeDisplayContext_TreeItem_Selected.toString(), treedisplaycontext_treeitem_selected.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TreeDisplayContext_Tree
	 */
	public final treeview.proxies.Tree getTreeDisplayContext_Tree() throws com.mendix.core.CoreException
	{
		return getTreeDisplayContext_Tree(getContext());
	}

	/**
	 * @param context
	 * @return value of TreeDisplayContext_Tree
	 * @throws com.mendix.core.CoreException
	 */
	public final treeview.proxies.Tree getTreeDisplayContext_Tree(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		treeview.proxies.Tree result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TreeDisplayContext_Tree.toString());
		if (identifier != null) {
			result = treeview.proxies.Tree.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TreeDisplayContext_Tree
	 * @param treedisplaycontext_tree
	 */
	public final void setTreeDisplayContext_Tree(treeview.proxies.Tree treedisplaycontext_tree)
	{
		setTreeDisplayContext_Tree(getContext(), treedisplaycontext_tree);
	}

	/**
	 * Set value of TreeDisplayContext_Tree
	 * @param context
	 * @param treedisplaycontext_tree
	 */
	public final void setTreeDisplayContext_Tree(com.mendix.systemwideinterfaces.core.IContext context, treeview.proxies.Tree treedisplaycontext_tree)
	{
		if (treedisplaycontext_tree == null) {
			getMendixObject().setValue(context, MemberNames.TreeDisplayContext_Tree.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TreeDisplayContext_Tree.toString(), treedisplaycontext_tree.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return treeDisplayContextMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final treeview.proxies.TreeDisplayContext that = (treeview.proxies.TreeDisplayContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
