// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aqhandlebars.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the AqHandlebars module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SaveCustomHelperRegisterBuilder(
		aqhandlebars.proxies.CustomHelperRegister _customHelperRegister
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AqHandlebars.ACT_SaveCustomHelperRegister");
		builder = builder.withParam("CustomHelperRegister", _customHelperRegister);
		return builder;
	}

	public static void aCT_SaveCustomHelperRegister(
		IContext context,
		aqhandlebars.proxies.CustomHelperRegister _customHelperRegister
	)
	{
		aCT_SaveCustomHelperRegisterBuilder(
				_customHelperRegister
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SavePartialTemplateBuilder(
		aqhandlebars.proxies.PartialTemplate _partialTemplate
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AqHandlebars.ACT_SavePartialTemplate");
		builder = builder.withParam("PartialTemplate", _partialTemplate);
		return builder;
	}

	public static void aCT_SavePartialTemplate(
		IContext context,
		aqhandlebars.proxies.PartialTemplate _partialTemplate
	)
	{
		aCT_SavePartialTemplateBuilder(
				_partialTemplate
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_ValidateCustomHelperRegisterBuilder(
		aqhandlebars.proxies.CustomHelperRegister _customHelperRegister
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AqHandlebars.SUB_ValidateCustomHelperRegister");
		builder = builder.withParam("CustomHelperRegister", _customHelperRegister);
		return builder;
	}

	public static boolean sUB_ValidateCustomHelperRegister(
		IContext context,
		aqhandlebars.proxies.CustomHelperRegister _customHelperRegister
	)
	{
		Object result = sUB_ValidateCustomHelperRegisterBuilder(
				_customHelperRegister
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_ValidatePartialTemplateBuilder(
		aqhandlebars.proxies.PartialTemplate _partialTemplate
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("AqHandlebars.SUB_ValidatePartialTemplate");
		builder = builder.withParam("PartialTemplate", _partialTemplate);
		return builder;
	}

	public static boolean sUB_ValidatePartialTemplate(
		IContext context,
		aqhandlebars.proxies.PartialTemplate _partialTemplate
	)
	{
		Object result = sUB_ValidatePartialTemplateBuilder(
				_partialTemplate
			)
			.execute(context);
		return (boolean) result;
	}
}
