// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package aqcommon.proxies;

public class CustomMapHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject customMapHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AqCommon.CustomMapHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SourceObjectAttributeName("SourceObjectAttributeName"),
		TargetObjectAttributeName("TargetObjectAttributeName");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CustomMapHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CustomMapHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customMapHelperMendixObject)
	{
		if (customMapHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, customMapHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.customMapHelperMendixObject = customMapHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static aqcommon.proxies.CustomMapHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new aqcommon.proxies.CustomMapHelper(context, mendixObject);
	}

	public static aqcommon.proxies.CustomMapHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return aqcommon.proxies.CustomMapHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of SourceObjectAttributeName
	 */
	public final java.lang.String getSourceObjectAttributeName()
	{
		return getSourceObjectAttributeName(getContext());
	}

	/**
	 * @param context
	 * @return value of SourceObjectAttributeName
	 */
	public final java.lang.String getSourceObjectAttributeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SourceObjectAttributeName.toString());
	}

	/**
	 * Set value of SourceObjectAttributeName
	 * @param sourceobjectattributename
	 */
	public final void setSourceObjectAttributeName(java.lang.String sourceobjectattributename)
	{
		setSourceObjectAttributeName(getContext(), sourceobjectattributename);
	}

	/**
	 * Set value of SourceObjectAttributeName
	 * @param context
	 * @param sourceobjectattributename
	 */
	public final void setSourceObjectAttributeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sourceobjectattributename)
	{
		getMendixObject().setValue(context, MemberNames.SourceObjectAttributeName.toString(), sourceobjectattributename);
	}

	/**
	 * @return value of TargetObjectAttributeName
	 */
	public final java.lang.String getTargetObjectAttributeName()
	{
		return getTargetObjectAttributeName(getContext());
	}

	/**
	 * @param context
	 * @return value of TargetObjectAttributeName
	 */
	public final java.lang.String getTargetObjectAttributeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TargetObjectAttributeName.toString());
	}

	/**
	 * Set value of TargetObjectAttributeName
	 * @param targetobjectattributename
	 */
	public final void setTargetObjectAttributeName(java.lang.String targetobjectattributename)
	{
		setTargetObjectAttributeName(getContext(), targetobjectattributename);
	}

	/**
	 * Set value of TargetObjectAttributeName
	 * @param context
	 * @param targetobjectattributename
	 */
	public final void setTargetObjectAttributeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String targetobjectattributename)
	{
		getMendixObject().setValue(context, MemberNames.TargetObjectAttributeName.toString(), targetobjectattributename);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return customMapHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final aqcommon.proxies.CustomMapHelper that = (aqcommon.proxies.CustomMapHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
