// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqcommon.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.thirdparty.org.json.JSONArray;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class AddStringFieldToJsonObject extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String JsonObject;
	private final java.lang.String FieldKey;
	private final java.lang.String FieldValue;

	public AddStringFieldToJsonObject(
		IContext context,
		java.lang.String _jsonObject,
		java.lang.String _fieldKey,
		java.lang.String _fieldValue
	)
	{
		super(context);
		this.JsonObject = _jsonObject;
		this.FieldKey = _fieldKey;
		this.FieldValue = _fieldValue;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		JSONObject jsonObject = new JSONObject(JsonObject);
		jsonObject.put(FieldKey, FieldValue);
		
		return jsonObject.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddStringFieldToJsonObject";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
