// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqcommon.actions;

import com.mendix.core.objectmanagement.DataValidationInfo;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class AddValidationFeedback extends CustomJavaAction<java.lang.Void>
{
	private final IMendixObject MxObject;
	private final java.lang.String AttributeName;
	private final java.lang.String ValidationMessage;

	public AddValidationFeedback(
		IContext context,
		IMendixObject _mxObject,
		java.lang.String _attributeName,
		java.lang.String _validationMessage
	)
	{
		super(context);
		this.MxObject = _mxObject;
		this.AttributeName = _attributeName;
		this.ValidationMessage = _validationMessage;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		DataValidationInfo dataValidationInfo = new DataValidationInfo(MxObject.getId().toLong());
		dataValidationInfo.addErrorField(AttributeName, ValidationMessage);
		getContext().addDataValidation(dataValidationInfo);
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddValidationFeedback";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
