// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqcommon.actions;

import java.io.InputStream;
import com.mendix.core.Core;
import com.mendix.core.objectmanagement.member.MendixBoolean;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import system.proxies.FileDocument;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CloneFileDocument extends CustomJavaAction<java.lang.Boolean>
{
	/** @deprecated use CloneSource.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CloneSource;
	private final system.proxies.FileDocument CloneSource;
	/** @deprecated use CloneTarget.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __CloneTarget;
	private final system.proxies.FileDocument CloneTarget;

	public CloneFileDocument(
		IContext context,
		IMendixObject _cloneSource,
		IMendixObject _cloneTarget
	)
	{
		super(context);
		this.__CloneSource = _cloneSource;
		this.CloneSource = _cloneSource == null ? null : system.proxies.FileDocument.initialize(getContext(), _cloneSource);
		this.__CloneTarget = _cloneTarget;
		this.CloneTarget = _cloneTarget == null ? null : system.proxies.FileDocument.initialize(getContext(), _cloneTarget);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (__CloneSource == null || __CloneTarget == null) {
			throw new Exception("At least one of the provided FileDocument objects is null");
		}

		if (!CloneSource.getHasContents()) {
			return false;
		}

		try (InputStream inputStream = Core.getFileDocumentContent(getContext(), __CloneSource)) {
			Core.storeFileDocumentContent(getContext(), __CloneTarget, CloneSource.getName(), inputStream);
		}

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CloneFileDocument";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
