// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqcommon.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CompleteWorkflowTask extends CustomJavaAction<java.lang.Void>
{
	/** @deprecated use WorkflowUserTask.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __WorkflowUserTask;
	private final system.proxies.WorkflowUserTask WorkflowUserTask;
	private final java.lang.String Outcome;

	public CompleteWorkflowTask(
		IContext context,
		IMendixObject _workflowUserTask,
		java.lang.String _outcome
	)
	{
		super(context);
		this.__WorkflowUserTask = _workflowUserTask;
		this.WorkflowUserTask = _workflowUserTask == null ? null : system.proxies.WorkflowUserTask.initialize(getContext(), _workflowUserTask);
		this.Outcome = _outcome;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		com.mendix.workflows.UserTask userTask = Core.workflows().getUserTask(getContext(), WorkflowUserTask.getMendixObject());
		userTask.complete(Outcome);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CompleteWorkflowTask";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
