// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package aqcommon.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import aqcommon.customexportmapping.JsonTransformer;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ExportToJsonWithCustomMapping extends CustomJavaAction<java.lang.String>
{
	private final java.lang.String MappingDefinition;
	private final IMendixObject RootObject;

	public ExportToJsonWithCustomMapping(
		IContext context,
		java.lang.String _mappingDefinition,
		IMendixObject _rootObject
	)
	{
		super(context);
		this.MappingDefinition = _mappingDefinition;
		this.RootObject = _rootObject;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		JsonTransformer jsonTransformer = null;
		
		if(RootObject == null) {
			jsonTransformer = new JsonTransformer(MappingDefinition);
		}
		else {
			jsonTransformer = new JsonTransformer(MappingDefinition, RootObject, getContext());
		}
		
		return jsonTransformer.transform();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ExportToJsonWithCustomMapping";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
