// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package treeview.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the TreeView module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCr_TreeItemBuilder(
		treeview.proxies.TreeItem _treeItem
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TreeView.ACr_TreeItem");
		builder = builder.withParam("TreeItem", _treeItem);
		return builder;
	}

	public static void aCr_TreeItem(
		IContext context,
		treeview.proxies.TreeItem _treeItem
	)
	{
		aCr_TreeItemBuilder(
				_treeItem
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AddTreeItem_RootBuilder(
		treeview.proxies.Tree _tree
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TreeView.ACT_AddTreeItem_Root");
		builder = builder.withParam("Tree", _tree);
		return builder;
	}

	public static void aCT_AddTreeItem_Root(
		IContext context,
		treeview.proxies.Tree _tree
	)
	{
		aCT_AddTreeItem_RootBuilder(
				_tree
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_NewTreeItem_ChildBuilder(
		treeview.proxies.TreeItem _treeItem,
		treeview.proxies.Tree _tree
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TreeView.ACT_NewTreeItem_Child");
		builder = builder.withParam("TreeItem", _treeItem);
		builder = builder.withParam("Tree", _tree);
		return builder;
	}

	public static void aCT_NewTreeItem_Child(
		IContext context,
		treeview.proxies.TreeItem _treeItem,
		treeview.proxies.Tree _tree
	)
	{
		aCT_NewTreeItem_ChildBuilder(
				_treeItem,
				_tree
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SaveNewTreeBuilder(
		treeview.proxies.Tree _tree
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TreeView.ACT_SaveNewTree");
		builder = builder.withParam("Tree", _tree);
		return builder;
	}

	public static void aCT_SaveNewTree(
		IContext context,
		treeview.proxies.Tree _tree
	)
	{
		aCT_SaveNewTreeBuilder(
				_tree
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SaveTreeItemBuilder(
		treeview.proxies.TreeItem _treeItem
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TreeView.ACT_SaveTreeItem");
		builder = builder.withParam("TreeItem", _treeItem);
		return builder;
	}

	public static void aCT_SaveTreeItem(
		IContext context,
		treeview.proxies.TreeItem _treeItem
	)
	{
		aCT_SaveTreeItemBuilder(
				_treeItem
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_ChildTreeItemsBuilder(
		treeview.proxies.TreeItem _treeItem
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TreeView.DS_ChildTreeItems");
		builder = builder.withParam("TreeItem", _treeItem);
		return builder;
	}

	public static java.util.List<treeview.proxies.TreeItem> dS_ChildTreeItems(
		IContext context,
		treeview.proxies.TreeItem _treeItem
	)
	{
		Object result = dS_ChildTreeItemsBuilder(
				_treeItem
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> treeview.proxies.TreeItem.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_TreeDisplayContextBuilder(
		treeview.proxies.Tree _tree
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TreeView.DS_TreeDisplayContext");
		builder = builder.withParam("Tree", _tree);
		return builder;
	}

	public static treeview.proxies.TreeDisplayContext dS_TreeDisplayContext(
		IContext context,
		treeview.proxies.Tree _tree
	)
	{
		Object result = dS_TreeDisplayContextBuilder(
				_tree
			)
			.execute(context);
		return result == null ? null : treeview.proxies.TreeDisplayContext.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder wDG_TreeItem_SelectedBuilder(
		treeview.proxies.TreeItem _treeItem,
		treeview.proxies.TreeDisplayContext _treeDisplayContext
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("TreeView.WDG_TreeItem_Selected");
		builder = builder.withParam("TreeItem", _treeItem);
		builder = builder.withParam("TreeDisplayContext", _treeDisplayContext);
		return builder;
	}

	public static void wDG_TreeItem_Selected(
		IContext context,
		treeview.proxies.TreeItem _treeItem,
		treeview.proxies.TreeDisplayContext _treeDisplayContext
	)
	{
		wDG_TreeItem_SelectedBuilder(
				_treeItem,
				_treeDisplayContext
			)
			.execute(context);
	}
}
